// frontend/react/src/components/SkuList.tsx

import React, { useEffect, useState } from 'react';
import { useQuery } from '@apollo/client';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import Box from '@mui/material/Box';
import { useNavigate } from 'react-router';
import { SkusQuery, SkusQueryVariables, SkuList as Skus } from '../graphql/types';
import Paper from '@mui/material/Paper';
import { Typography } from '@mui/material';
import { SKU_LIST } from '../graphql/skus.graphql';
import { OFFSET_DEFAULT, LIMIT_DEFAULT } from './ListDefaults';
import { useSearchParams } from 'react-router-dom';

const columns: GridColDef[] = [
  {
    field: 'skuKey', headerName: 'Key', width: 90, valueGetter: (params) => {
      return params.row.skuKey;
    },
  },
  {
    field: 'name',
    headerName: 'Name',
    width: 200,
  },
  {
    field: 'description',
    headerName: 'Description',
    width: 500,
  },
  {
    field: 'price',
    headerName: 'Price',
    type: 'number',
    width: 110,
    valueGetter: (params) => {
      return params.row.price;
    },
  },
  {
    field: 'quantity',
    headerName: 'Quantity',
    type: 'number',
    width: 110,
    valueGetter: (params) => {
      return params.row.quantity;
    },
  },
];


export function SkusMain() {
  return (
    <div>
      <Typography variant="h4" gutterBottom>SKUs</Typography>
      <SkuList />
    </div>
  );
}

export function SkuList() {
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams({ offset: OFFSET_DEFAULT.toString(), limit: LIMIT_DEFAULT.toString() });
  const [skuList, setSkuList] = useState<Skus>({ skus: [], offset: OFFSET_DEFAULT, limit: LIMIT_DEFAULT, totalCount: LIMIT_DEFAULT });
  const { data, error, loading, fetchMore } = useQuery<SkusQuery, SkusQueryVariables>(
    SKU_LIST,
    {
      variables: {
        offset: skuList.offset,
        limit: skuList.limit
      },
      fetchPolicy: 'cache-first',
    }
  );

  useEffect(() => {
    if (data && data.skus) {
      setSearchParams({
        offset: data.skus.offset?.toString() || OFFSET_DEFAULT.toString(),
        limit: data.skus.limit?.toString() || LIMIT_DEFAULT.toString(),
      });
      setSkuList({
        offset: data.skus.offset || OFFSET_DEFAULT,
        limit: data.skus.limit || LIMIT_DEFAULT,
        totalCount: data.skus.totalCount || LIMIT_DEFAULT,
        skus: data.skus.skus || []
      });
    }
  }, [data]);

  function fetchNext(offset: number, limit: number) {
    console.debug("[SkuList.fetchNext]",
      offset, limit);
    fetchMore({
      variables: {
        offset,
        limit
      },
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        if (!fetchMoreResult) return prev;
        console.debug("[SkuListComponent.fetchNext.updateQuery]",
          prev,
          fetchMoreResult);
        setSkuList({
          offset: fetchMoreResult.skus.offset || skuList.offset,
          limit: fetchMoreResult.skus.limit || skuList.limit,
          totalCount: fetchMoreResult.skus.totalCount || skuList.totalCount,
          skus: fetchMoreResult.skus.skus || []
        });
      }
    });
    return;
  }


  console.log('[SkuList] result', data, error, loading);
  console.log('[SkuList] pagination', skuList);
  console.log('[SkuList] searchParams', searchParams);

  return (
    <Paper square={false}
      elevation={6}>

      {error && <p>Error: {error.message}</p>}
      <Box m={2}>
        <Typography variant="h6" gutterBottom>Click on a SKU to see details</Typography>
        <DataGrid
          sx={{ minHeight: 400 }}
          rows={(skuList.skus) ? skuList.skus.map(value => {
            return {
              id: value?.skuKey,
              ...value
            };
          }) : []}
          columns={columns}
          loading={loading}
          initialState={{
            pagination: {
              paginationModel: {
                pageSize: LIMIT_DEFAULT,
                page: OFFSET_DEFAULT / LIMIT_DEFAULT,
              },
            },
          }}
          rowCount={skuList.totalCount || 0}
          paginationMode='server'
          pageSizeOptions={[LIMIT_DEFAULT]}
          onPaginationModelChange={({ pageSize, page }) => {
            console.debug("[SkuList.onPaginationModelChange]", page, pageSize);
            fetchNext(pageSize * page, pageSize);
          }}
          onRowClick={(row) => navigate(`${row.row.id}`)}
        />
      </Box>
    </Paper>
  );
}

// frontend/angular/src/app/sku-list/sku-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { Sku, SkusQuery, SkusQueryVariables } from 'not-dsp-graphql';
import { Apollo } from 'apollo-angular';
import { ActivatedRoute, Router } from '@angular/router';
import { SKU_LIST } from '../graphql/skus.graphql';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';




@Component({
  selector: 'app-sku-list',
  templateUrl: './sku-list.component.html',
  styleUrls: ['./sku-list.component.css']
})
export class SkuListComponent implements OnInit {
  displayedColumns: string[] = ['skuKey', 'name', 'description', 'price', 'quantity'];

  skus: Sku[] = [];
  displaySku: Sku[] = [];
  loading: boolean = true;
  error: any;
  datasource = new MatTableDataSource<Sku>();

  offset: number = 0;
  limit: number = 5;
  skusCount: number = 15;

  page: number = 0;

  skusQuery: any | undefined;

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  constructor(private apollo: Apollo, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.skusQuery = this.apollo.watchQuery<SkusQuery, SkusQueryVariables>({
      query: SKU_LIST,
      variables: {
        offset: this.offset,
        limit: this.limit
      },
      fetchPolicy: 'cache-and-network'
    });
    this.skusQuery.valueChanges.subscribe((result: any) => {
      this.skus = result.data.skus?.skus ? result.data.skus?.skus as Sku[] : [];
      // this.datasource.data = mockSKUs.slice(this.offset, this.offset + this.limit);
      this.datasource.data = this.skus.slice(this.offset, this.offset + this.limit);
      this.loading = result.loading;
      this.error = result.errors;
      this.skusCount = result.data.skus?.totalCount;
      this.offset = result.data.skus?.offset;
      this.limit = result.data.skus?.limit;
      // this.page = this.offset / this.limit;
      console.debug('[SkuListComponent.ngOnInit] offset, limit, page', this.offset, this.limit, this.page);
      console.debug('[SkuListComponent.ngOnInit] skus', result.data.skus);
    });

  }

  ngAfterViewInit() {
    console.debug("ngAfterViewInit");
    this.paginator.page.subscribe(page => {
      console.debug('[SkuListComponent.ngAfterViewInit] page event', page);
      const newPageindex = page.pageIndex;
      const previousPageindex = page.previousPageIndex || 0;

      this.offset = page.pageIndex * this.limit;
      this.page = this.offset / this.limit;
      this.limit = page.pageSize;
      console.debug('[SkuListComponent.ngAfterViewInit] offset, limit, page',
        this.offset, this.limit, this.page);
      console.debug('[SkuListComponent.ngAfterViewInit] skus',
        this.skus);

      if (newPageindex > previousPageindex)
        this.fetchNext(this.offset, this.limit);
      else
        this.fetchPrevious(this.offset, this.limit);
    });
  }

  fetchPrevious(offset: number, limit: number) {
    console.debug("[SkuListComponent.fetchPrevious]", offset, limit);
    this.datasource.data = this.skus.slice(offset, offset + limit);
  }

  fetchNext(offset: number, limit: number) {
    console.debug("[SkuListComponent.fetchNext]",
      offset, limit);
    this.skusQuery?.fetchMore({
      variables: {
        offset,
        limit
      },
      fetchPolicy: 'cache-and-network',
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        if (!fetchMoreResult) return prev;
        console.debug("[SkuListComponent.fetchNext.updateQuery]",
          prev,
          fetchMoreResult);
        const merged = Object.assign({}, prev, {
          skus: {
            ...prev.skus,
            skus: [...fetchMoreResult.skus.skus],
            offset,
            limit,
            totalCount: fetchMoreResult.skus.totalCount
          }
        });
        this.datasource.data = this.skus.slice(offset, offset + limit);
        return merged;
      }
    });
    return;
  }

  clickedRow(row: Sku) {
    console.debug('[SkuListComponent] clicked row', row);
    this.router.navigate(['/skus', row.skuKey]);
  }
}


<div *ngIf="error">
  <p>Error: {{ error }}</p>
</div>
<mat-card>
  <mat-card-header>
    <mat-card-title>SKUs</mat-card-title>

  </mat-card-header>
  <mat-card-content>
  <mat-table [dataSource]="datasource" class="mat-elevation-z8">
    <ng-container matColumnDef="skuKey">
      <th mat-header-cell *matHeaderCellDef> Key </th>
      <td mat-cell *matCellDef="let element"> {{element.skuKey}} </td>
    </ng-container>
    <ng-container matColumnDef="name">
      <th mat-header-cell *matHeaderCellDef> Name </th>
      <td mat-cell *matCellDef="let element"> {{element.name}} </td>
    </ng-container>
    <ng-container matColumnDef="description">
      <th mat-header-cell *matHeaderCellDef> Description </th>
      <td mat-cell *matCellDef="let element"> {{element.description.substring(0,75)}} </td>
    </ng-container>
    <ng-container matColumnDef="quantity">
      <th mat-header-cell *matHeaderCellDef> Quantity </th>
      <td mat-cell *matCellDef="let element"> {{element.quantity}} </td>
    </ng-container>
    <ng-container matColumnDef="price">
      <th mat-header-cell *matHeaderCellDef> Price </th>
      <td mat-cell *matCellDef="let element"> {{element.price}} </td>
    </ng-container>

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row (click)="clickedRow(row)"
    *matRowDef="let row; columns: displayedColumns;"></tr>
  </mat-table>
  <mat-paginator #paginator
    [pageSizeOptions]="[5, 10, 20]"
    [pageSize]="limit"
    [pageIndex]="page"
    showFirstLastButtons
    [length]="skusCount"
    aria-label="Select page of SKUs">
  </mat-paginator>
<div *ngIf="loading">
      <mat-progress-bar mode="indeterminate"></mat-progress-bar>
    </div>
</mat-card-content>
</mat-card>
