// frontend/react/src/components/BrandDetails.tsx
import React from 'react';
import {
  Paper, TextField, Link,
  LinearProgress, Stack, Card, CardHeader, CardContent,
} from '@mui/material';
import { useQuery } from '@apollo/client';
import { useParams } from 'react-router-dom';
import { BrandQuery, BrandQueryVariables } from 'not-dsp-graphql';
import { BRAND_DETAILS } from 'not-dsp-graphql';
import { ErrorNofification } from './error/ErrorBoundary';

export function BrandDetails() {
  const params = useParams();

  const { data, loading, error } = useQuery<BrandQuery, BrandQueryVariables>(BRAND_DETAILS,
    {
      variables: {
        brandId: params.brandId || 'no-id',
      }
    });

  console.log('params', params);
  return (

    <Card elevation={6}
      sx={{
        '& .MuiTextField-root': { m: 1, width: '55ch' },
      }}>
      <CardHeader
        title={'Brand'}
        subheader={<Link
          href={(data && data.brand && data.brand.website) ? data.brand.website : ''}
          target='_blank'>website</Link>}
      />
      <CardContent
        component="form"
        noValidate
        autoComplete="off">
        {loading && <LinearProgress variant="query" />}
        {error && <ErrorNofification error={error} />}
        <Stack spacing={1}>
          <TextField
            label="ID"
            value={(data && data.brand) ? data?.brand?.id : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Name"
            value={(data && data.brand) ? data?.brand?.name : ''}
            InputProps={{
              readOnly: true,
            }} />


          <TextField
            label="Country"
            value={(data && data.brand) ? data?.brand?.country : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Industry"
            value={(data && data.brand) ? data?.brand?.industry : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Founded in"
            value={(data && data.brand) ? data?.brand?.foundedIn : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Founded by"
            value={(data && data.brand) ? data?.brand?.foundedBy : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Rank"
            value={(data && data.brand) ? data?.brand?.rank : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Rating"
            value={(data && data.brand) ? data?.brand?.rating : ''}
            InputProps={{
              readOnly: true,
            }} />
          <TextField
            label="Brand Value USD(m)"
            value={(data && data.brand) ? data?.brand?.brandValue : ''}
            InputProps={{
              readOnly: true,
            }} />
        </Stack>
      </CardContent>
    </Card>
  );
}

// frontend/angular/src/app/brand-details/brand-details.component.ts
import { Component } from '@angular/core';
import { Brand, BrandQuery, BrandQueryVariables, Sku } from 'not-dsp-graphql';
import { BRAND_DETAILS } from 'not-dsp-graphql';
import { Apollo } from 'apollo-angular';
import { ActivatedRoute } from '@angular/router';
import { DetailsComponent } from '../detail-component';

@Component({
  selector: 'app-brand-details',
  templateUrl: './brand-details.component.html',
  styleUrls: ['./brand-details.component.css']
})
export class BrandDetailsComponent extends DetailsComponent {

  brand: Brand | undefined = undefined;
  loading: boolean = true;

  ngOnInit(): void {
    const id = this.route.snapshot.params['brandId'];
    this.apollo.watchQuery<BrandQuery, BrandQueryVariables>({
      query: BRAND_DETAILS,
      variables: {
        brandId: id
      }
    }).valueChanges.subscribe((result) => {
      console.log(result);
      this.brand = result.data.brand ? result.data.brand as Brand : undefined;
      this.loading = result.loading;
      this.displayError(result.error);
    });
  }
  saveDetails(form: any) {
    alert('Brand Form Validated)' + JSON.stringify(form.value, null, 4));
  }
}

<mat-card>
  <mat-card-header>
    <mat-card-title>Brand details {{ brand ? brand.id : "" }}</mat-card-title>
    <mat-progress-bar *ngIf="loading" mode="indeterminate"></mat-progress-bar>
  </mat-card-header>

  <mat-card-content *ngIf="brand">
    <mat-form-field>
      <mat-label>Name:</mat-label>
      <input matInput value="{{ brand.name }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Country:</mat-label>
      <input matInput value="{{ brand.country }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Country:</mat-label>
      <input matInput value="{{ brand.country }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Industry:</mat-label>
      <input matInput value="{{ brand.industry }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Founded in:</mat-label>
      <input matInput value="{{ brand.foundedIn }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Founded by:</mat-label>
      <input matInput value="{{ brand.foundedBy }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Rank:</mat-label>
      <input matInput value="{{ brand.rank }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Rating:</mat-label>
      <input matInput value="{{ brand.rating }}" />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Brand Value USD(m):</mat-label>
      <input matInput value="{{ brand.brandValue }}" />
    </mat-form-field>
  </mat-card-content>
</mat-card>
