// frontend/react/src/components/PortfolioDetails.tsx
import { Alert, AlertTitle, Button, Card, CardActions, CardContent, CardHeader, FormControl, FormLabel, LinearProgress, Snackbar, Stack, TextField } from '@mui/material';
import { TextareaAutosize } from '@mui/base/TextareaAutosize';
import React, { useEffect, useMemo, useState } from 'react';
import { ErrorNofification } from './error/ErrorBoundary';
import { useNavigate, useParams } from 'react-router-dom';
import { Account, Brand, LIST_PORTFOLIOS, MAP_PORTFOLIO_ACCOUNTS, MAP_PORTFOLIO_BRANDS, MAP_PORTFOLIO_USERS, MapAccountsToPortfolioMutation, MapAccountsToPortfolioMutationVariables, MapBrandsToPortfolioMutation, MapBrandsToPortfolioMutationVariables, MapUsersToPortfolioMutation, MapUsersToPortfolioMutationVariables, NEW_PORTFOLIO, NewPortfolioMutation, NewPortfolioMutationVariables, PORTFOLIO_ACCOUNTS_MODIFIED, PORTFOLIO_BRANDS_MODIFIED, PORTFOLIO_DETAILS, PORTFOLIO_USERS_MODIFIED, Portfolio, PortfolioAccountsModifiedSubscription, PortfolioAccountsModifiedSubscriptionVariables, PortfolioBrandsModifiedSubscription, PortfolioBrandsModifiedSubscriptionVariables, PortfolioQuery, PortfolioQueryVariables, PortfolioUsersModifiedSubscription, PortfolioUsersModifiedSubscriptionVariables, User } from 'not-dsp-graphql';
import { ApolloError, useMutation, useQuery, useSubscription } from '@apollo/client';
import { UserChooser } from './UserChooser';
import { AccountChooser } from './AccountChooser';
import { BrandChooser } from './BrandChooser';
import { useErrorBoundary } from 'react-error-boundary';
import { SNACKBAR_AUTOHIDE_DURATION } from '../lib/utility';

export function PortfolioDetails() {
  const params = useParams();
  const navigate = useNavigate();
  const { showBoundary } = useErrorBoundary();
  const [isNew] = useState(params.portfolioId === 'new');
  const portfolioId = useMemo(() => {
    return params.portfolioId || 'new';
  }, [params.portfolioId]);
  const [portfolio, setPortfolio] = useState<Portfolio>({
    id: 'no-id',
    name: '',
    description: '',
    users: [],
    brands: [],
    accounts: [],
  });

  const [newPortfolio, { loading: createLoading, error: createError }] = useMutation<NewPortfolioMutation, NewPortfolioMutationVariables>(
    NEW_PORTFOLIO);
  const [mapUsers, { loading: mapUsersLoading, error: mapUsersError }] = useMutation<MapUsersToPortfolioMutation, MapUsersToPortfolioMutationVariables>(
    MAP_PORTFOLIO_USERS);
  const [mapAccounts, { loading: mapAccountsLoading, error: mapAccountsError }] = useMutation<MapAccountsToPortfolioMutation, MapAccountsToPortfolioMutationVariables>(
    MAP_PORTFOLIO_ACCOUNTS);
  const [mapBrands, { loading: mapBrandsLoading, error: mapBrandsError }] = useMutation<MapBrandsToPortfolioMutation, MapBrandsToPortfolioMutationVariables>(
    MAP_PORTFOLIO_BRANDS);

  const { data, loading, error } = useQuery<PortfolioQuery, PortfolioQueryVariables>(PORTFOLIO_DETAILS,
    {
      variables: {
        portfolioId
      },
      skip: isNew,
    });
  if (error) showBoundary(error);

  useEffect(() => {
    if (!isNew && data) {
      console.debug('[PortfolioDetails.useEffect] data', data);
      setPortfolio(data.portfolio as Portfolio);
    }
  }, [data, isNew]);

  function handleInputChange(e: any) {
    const { name, value } = e.target;
    setPortfolio({
      ...portfolio,
      [name]: value,
    });
  }

  function createPortfolio() {
    console.debug('[PortfolioDetails.createPortfolio] args');
    newPortfolio({
      variables: {
        portfolio: {
          name: portfolio.name as string,
          description: portfolio.description as string,
          brandIds: portfolio.brands?.map(b => b ? b.id : null) || [],
          accountIds: portfolio.accounts?.map(a => a ? a.id : null) || [],
          userIds: portfolio.users?.map(u => u ? u.id : null) || [],
        }
      },
      refetchQueries: [{
        query: LIST_PORTFOLIOS
      }],
      onCompleted: (data: NewPortfolioMutation) => {
        console.debug('[PortfolioDetails.createPortfolio]  completed', data);
        navigate(-1);
      },
      onError: (error: ApolloError) => {
        console.error('[PortfolioDetails.createPortfolio] error', error);
        if (error) showBoundary(error);
      }
    });
  }

  function updatePortfolio() {
    alert('[PortfolioDetails.updatePortfolio] Method not implemented.');
    navigate(-1);
  }


  function onFormSubmit() {
    console.debug('[PortfolioDetails.onFormSubmit] portfolio', portfolio);
    if (isNew) {
      createPortfolio();
    } else {
      updatePortfolio();
    }
  }

  function chosenUsers(users: User[]) {
    console.debug('[PortfolioDetails.chosenUsers]', users);

    setPortfolio({
      ...portfolio,
      users: users
    });
    if (!isNew) {
      mapUsers({
        variables: {
          portfolioId: portfolio.id as string,
          userIds: users.map(u => u.id),
        },
        refetchQueries: [{
          query: PORTFOLIO_DETAILS,
          variables: {
            portfolioId: portfolio.id
          }
        }],
        onCompleted: (data: NewPortfolioMutation) => {
          console.debug('[PortfolioDetails.chosenUsers]  completed', data);
        },
        onError: (error: ApolloError) => {
          console.error('[PortfolioDetails.chosenUsers] error', error);
          if (error) showBoundary(error);
        }
      });
    }
  }

  function chosenBrands(brands: Brand[]) {
    console.debug('[PortfolioDetails.chosenBrands]', brands);
    setPortfolio({
      ...portfolio,
      brands: brands,
    });
    if (!isNew) {
      mapBrands({
        variables: {
          portfolioId: portfolio.id as string,
          brandIds: brands.map(b => b.id),
        },
        refetchQueries: [{
          query: PORTFOLIO_DETAILS,
          variables: {
            portfolioId: portfolio.id
          }
        }],
        onCompleted: (data: NewPortfolioMutation) => {
          console.debug('[PortfolioDetails.chosenBrands]  completed', data);

        },
        onError: (error: ApolloError) => {
          console.error('[PortfolioDetails.chosenBrands] error', error);
          if (error) showBoundary(error);
        }
      });
    }
  }

  function chosenAccounts(accounts: Account[]) {
    console.debug('[PortfolioDetails.chosenAccounts]', accounts);
    setPortfolio({
      ...portfolio,
      accounts: accounts,
    });
    if (!isNew) {
      mapAccounts({
        variables: {
          portfolioId: portfolio.id as string,
          accountIds: accounts.map(a => a.id),
        },
        refetchQueries: [{
          query: PORTFOLIO_DETAILS,
          variables: {
            portfolioId: portfolio.id
          }
        }],
        onCompleted: (data: NewPortfolioMutation) => {
          console.debug('[PortfolioDetails.chosenAccounts]  completed', data);

        },
        onError: (error: ApolloError) => {
          console.error('[PortfolioDetails.chosenAccounts] error', error);
          if (error) showBoundary(error);
        }
      });
    }

  }
  console.debug('[PortfolioDetails] portfolio', portfolio);
  return (
    <Card elevation={6}
    >
      <CardHeader
        title={`Portfolio: ${portfolioId}`} />
      <CardActions >
        {isNew && <Button type="submit" variant='contained' onClick={onFormSubmit}>Create</Button>}
      </CardActions>
      <CardContent

        component="form"
        noValidate
        autoComplete="off"
      >
        {!isNew && <UsersModified portfolioId={portfolio.id as string} />}
        {!isNew && <BrandsModified portfolioId={portfolio.id as string} />}
        {!isNew && <AccountsModified portfolioId={portfolio.id as string} />}
        {(loading || createLoading || mapUsersLoading) && <LinearProgress variant="query" />}
        <Stack spacing={2}>
          <TextField
            label="Name"
            name="name"
            id='name'
            value={portfolio.name}
            onChange={handleInputChange}
            size='small'
          />
          <TextField
            rows={5}
            multiline
            label="Description"
            name='description'
            id='description'
            value={portfolio.description as string}
            onChange={handleInputChange}
          />
          <UserChooser selectedValues={portfolio.users as User[]} chosenUsers={chosenUsers} />
          <AccountChooser selectedValues={portfolio.accounts as Account[]} chosenAccounts={chosenAccounts} />
          <BrandChooser selectedValues={portfolio.brands as Brand[]} chosenBrands={chosenBrands} />
        </Stack>
      </CardContent>
    </Card>
  );
}

export function UsersModified(props: { portfolioId: string; }) {
  const { data } = useSubscription<PortfolioUsersModifiedSubscription, PortfolioUsersModifiedSubscriptionVariables>(PORTFOLIO_USERS_MODIFIED,
    {
      variables: {
        portfolioId: props.portfolioId
      }
    });
  const [state, setState] = useState({ open: false, message: '' });
  useMemo(() => {
    if (data) {
      console.log('***', data);
      setState({ open: true, message: `Users for ${data?.portfolioUsersModified?.name} modified at ${new Date().toLocaleString()}` });
    }
  }, [data]);
  function onClose() {
    setState({ open: false, message: '' });
  }
  console.debug('[UsersModified] data props', data, props);
  return (
    <Snackbar open={state.open}
      autoHideDuration={SNACKBAR_AUTOHIDE_DURATION}
      onClose={onClose}
      anchorOrigin={{ vertical: 'top', horizontal: 'right' }}>
      <Alert onClose={onClose}>
        <AlertTitle>{state.message} </AlertTitle>
      </Alert>
    </Snackbar >
  );
}

export function BrandsModified(props: { portfolioId: string; }) {
  const { data } = useSubscription<PortfolioBrandsModifiedSubscription, PortfolioBrandsModifiedSubscriptionVariables>(PORTFOLIO_BRANDS_MODIFIED,
    {
      variables: {
        portfolioId: props.portfolioId
      }
    });
  const [state, setState] = useState({ open: false, message: '' });
  useMemo(() => {
    if (data) {
      console.log('***', data);
      setState({ open: true, message: `Brands for ${data?.portfolioBrandsModified?.name} modified at ${new Date().toLocaleString()}` });
    }
  }, [data]);
  function onClose() {
    setState({ open: false, message: '' });
  }
  console.debug('[BrandsModified] data props', data, props);
  return (
    <Snackbar open={state.open}
      autoHideDuration={SNACKBAR_AUTOHIDE_DURATION}
      onClose={onClose}
      anchorOrigin={{ vertical: 'top', horizontal: 'right' }}>
      <Alert onClose={onClose}>
        <AlertTitle>{state.message} </AlertTitle>
      </Alert>
    </Snackbar >
  );
}

export function AccountsModified(props: { portfolioId: string; }) {
  const { data } = useSubscription<PortfolioAccountsModifiedSubscription, PortfolioAccountsModifiedSubscriptionVariables>(PORTFOLIO_ACCOUNTS_MODIFIED,
    {
      variables: {
        portfolioId: props.portfolioId
      }
    });
  const [state, setState] = useState({ open: false, message: '' });
  useMemo(() => {
    if (data) {
      console.log('***', data);
      setState({ open: true, message: `Accounts for ${data?.portfolioAccountsModified?.name} modified at ${new Date().toLocaleString()}` });
    }
  }, [data]);
  function onClose() {
    setState({ open: false, message: '' });
  }
  console.debug('[AccountsModified] data props', data, props);
  return (
    <Snackbar open={state.open}
      autoHideDuration={SNACKBAR_AUTOHIDE_DURATION}
      onClose={onClose}
      anchorOrigin={{ vertical: 'top', horizontal: 'right' }}>
      <Alert onClose={onClose}>
        <AlertTitle>{state.message} </AlertTitle>
      </Alert>
    </Snackbar >
  );
}

// frontend/angular/src/app/portfolio-details/portfolio-details.component.ts
import { Component } from '@angular/core';
import {
  Account, Brand, LIST_PORTFOLIOS, MAP_PORTFOLIO_ACCOUNTS,
  MAP_PORTFOLIO_BRANDS, MAP_PORTFOLIO_USERS,
  MapAccountsToPortfolioMutation, MapAccountsToPortfolioMutationVariables,
  MapBrandsToPortfolioMutation, MapBrandsToPortfolioMutationVariables,
  MapUsersToPortfolioMutation, MapUsersToPortfolioMutationVariables,
  NEW_PORTFOLIO, NewPortfolio, NewPortfolioMutation, NewPortfolioMutationVariables,
  PORTFOLIO_ACCOUNTS_MODIFIED, PORTFOLIO_BRANDS_MODIFIED,
  PORTFOLIO_DETAILS, PORTFOLIO_USERS_MODIFIED, Portfolio,
  PortfolioAccountsModifiedSubscription, PortfolioAccountsModifiedSubscriptionVariables,
  PortfolioBrandsModifiedSubscription, PortfolioBrandsModifiedSubscriptionVariables,
  PortfolioQuery, PortfolioQueryVariables,
  PortfolioUsersModifiedSubscription, PortfolioUsersModifiedSubscriptionVariables, User
} from 'not-dsp-graphql';
import { Location } from '@angular/common';
import { Apollo } from 'apollo-angular';
import { ActivatedRoute } from '@angular/router';
import { MatSnackBar } from '@angular/material/snack-bar';
import { notifyConfig } from '../snackBarDefaults';

@Component({
  selector: 'app-portfolio-details',
  templateUrl: './portfolio-details.component.html',
  styleUrls: ['./portfolio-details.component.css']
})
export class PortfolioDetailsComponent {
  portfolio: Portfolio | undefined = undefined;
  loading: boolean = true;
  error: any;
  isNew: boolean = false;

  constructor(private apollo: Apollo,
    private route: ActivatedRoute,
    private snackBar: MatSnackBar,
    private location: Location
  ) { }

  ngOnInit(): void {
    const id = this.route.snapshot.params['portfolioId'];
    this.isNew = id === 'new';
    if (this.isNew) {
      console.debug('new portfolio');
      this.loading = false;
      this.portfolio = {
        id: '',
        name: '',
        description: '',
        accounts: [],
        brands: [],
        users: []
      };
    } else {
      this.apollo.watchQuery<PortfolioQuery, PortfolioQueryVariables>({
        query: PORTFOLIO_DETAILS,
        variables: {
          portfolioId: id
        }
      }).valueChanges.subscribe((result) => {
        console.log(result);
        this.portfolio = result.data.portfolio ? result.data.portfolio as Portfolio : undefined;
        this.loading = result.loading;
        this.error = result.errors;
        if (this.error) {
          this.snackBar.open(`Portfolio error: ${JSON.stringify(this.error, null, 2)} `, 'OK');
        }
      });
    }
  }

  onFormSubmit() {
    console.debug('form submit', this.portfolio);
    if (this.isNew) {
      this.createPortfolio(this.portfolio);
    } else {
      // TODO: update portfolio
    }
  }

  createPortfolio(form: any) {
    const accountId = this.route.snapshot.params['accountId'];
    console.debug('create portfolio', this.portfolio, this.route.snapshot.params);

    const newAPortfolio: NewPortfolio = {
      name: this.portfolio?.name as string,
      description: this.portfolio?.description as string,
      brandIds: this.portfolio?.brands?.map(b => b ? b.id : null) || [],
      accountIds: this.portfolio?.accounts?.map(a => a ? a.id : null) || [],
      userIds: this.portfolio?.users?.map(u => u ? u.id : null) || [],

    };
    this.apollo.mutate<NewPortfolioMutation, NewPortfolioMutationVariables>({

      mutation: NEW_PORTFOLIO,
      variables: {
        portfolio: newAPortfolio
      },
      refetchQueries: [{
        query: LIST_PORTFOLIOS,
      },
      {
        query: PORTFOLIO_DETAILS,
      }],

    }).subscribe(({ data, errors, loading }) => {
      if (errors) {
        console.error('Error creating portfolio', errors);
        this.snackBar.open(`Error creating portfolio: ${errors[0].message} `, 'OK');
        this.location.back();
      }
      if (data) {
        console.debug('New portfolio created', JSON.stringify(data, null, 2));
        const newPortfolioId = (data as any).newPortfolio.id;
        this.snackBar.open(`New portfolio created, id: ${newPortfolioId} `, 'OK', notifyConfig);
        this.location.back();
      }
    });

  }

  saveDetails(form: any) {
    console.debug("[PortfolioDetailsComponent.saveDetails] clicked");
    alert('Product Form Validated)' + JSON.stringify(form.value, null, 4));
  }

}

<mat-card>
  <mat-card-header>
    <mat-card-title>Portfolio details</mat-card-title>
    <div *ngIf="loading">
      <mat-progress-bar mode="indeterminate"></mat-progress-bar>
    </div>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
  </mat-card-header>

  <mat-card-content>
    <div *ngIf="portfolio">
      <p>
        <mat-form-field class="formField">
          <mat-label>Id:</mat-label>
          <input matInput value="{{(portfolio.id)?portfolio.id:''}}" readonly>
        </mat-form-field>
      </p>

      <p>
        <mat-form-field class="formField">
          <mat-label>Name:</mat-label>
          <input matInput value="{{portfolio.name}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Desctiption:</mat-label>
          <textarea matInput rows="6">
            {{portfolio.description}}
          </textarea>
        </mat-form-field>
      </p>
      <p>
        <user-chooser *ngIf="portfolio && portfolio.users" [existingUsers]="portfolio.users" (currentUsers)="portfolioUsers($event)"></user-chooser>
      </p>
      <p>
        <account-chooser *ngIf="portfolio && portfolio.accounts" [existingAccounts]="portfolio.accounts" (currentAccounts)="portfolioAccounts($event)"></account-chooser>
      </p>
      <p>
        <brand-chooser *ngIf="portfolio && portfolio.brands" [existingBrands]="portfolio.brands" (currentBrands)="portfolioBrands($event)"></brand-chooser>
      </p>
    </div>
  </mat-card-content>
</mat-card>
