// frontend/angular/src/app/portfolio-list/portfolio-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { LIST_PORTFOLIOS, Portfolio, PortfoliosQuery, PortfoliosQueryVariables } from 'not-dsp-graphql';
import { Apollo } from 'apollo-angular';
import { ActivatedRoute, Router } from '@angular/router';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';


@Component({
  selector: 'app-portfolio-list',
  templateUrl: './portfolio-list.component.html',
  styleUrls: ['./portfolio-list.component.css']
})
export class PortfolioListComponent {
  displayedColumns: string[] = ['name', 'description'];

  portfolios: Portfolio[] = [];
  displaySku: Portfolio[] = [];
  loading: boolean = true;
  error: any;
  datasource = new MatTableDataSource<Portfolio>();

  portfoliosQuery: any | undefined;

  constructor(private apollo: Apollo, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.portfoliosQuery = this.apollo.watchQuery<PortfoliosQuery, PortfoliosQueryVariables>({
      query: LIST_PORTFOLIOS,
      fetchPolicy: 'cache-and-network'
    });
    this.portfoliosQuery.valueChanges.subscribe((result: any) => {
      this.portfolios = result.data.portfolios ? result.data.portfolios as Portfolio[] : [];
      this.datasource.data = this.portfolios;
      this.loading = result.loading;
      this.error = result.errors;
      console.debug('[PortfolioListComponent.ngOnInit] portfolios', result.data.portfolios);
    });

  }

  newPortfolio() {
    this.router.navigate(['/portfolios', 'new']);
  }


  clickedRow(row: Portfolio) {
    console.debug('[PortfolioListComponent.clickedRow] row', row);
    this.router.navigate(['/portfolios', row.id]);
  }
}

<mat-card  class="mat-elevation-z6 portfolio-list">
  <mat-card-header>
    <mat-card-title>Portfolios</mat-card-title>
    <mat-card-subtitle>Click on a Portfolio to see details</mat-card-subtitle>
  </mat-card-header>
  <mat-card-actions>
    <button mat-raised-button color="primary" (click)="newPortfolio()">New Portfolio</button>
  </mat-card-actions>
  <mat-card-content>
    <mat-progress-bar *ngIf="loading" mode="indeterminate"></mat-progress-bar>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
    <mat-table [dataSource]="datasource" >
      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef> Name </th>
        <td mat-cell *matCellDef="let element"> {{element.name}} </td>
      </ng-container>
      <ng-container matColumnDef="description">
        <th mat-header-cell *matHeaderCellDef> Description </th>
        <td mat-cell *matCellDef="let element"> {{element.description}} </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row (click)="clickedRow(row)"
      *matRowDef="let row; columns: displayedColumns;"></tr>
    </mat-table>
  </mat-card-content>
</mat-card>

// frontend/react/src/components/PortfolioList.tsx
import React, { useState } from 'react';
import { LIST_PORTFOLIOS, PortfoliosQuery, PortfoliosQueryVariables } from 'not-dsp-graphql';
import { DataGrid, GridColDef, GridRowSelectionModel, GridValueGetterParams } from '@mui/x-data-grid';
import { useMutation, useQuery } from '@apollo/client';
import { useNavigate, useParams } from 'react-router';
import { Card, CardHeader, CardActionArea, ButtonGroup, Button, CardContent } from '@mui/material';
import { LIMIT_DEFAULT } from '../lib/ListDefaults';
import { ErrorNofification } from './error/ErrorBoundary';

const columns: GridColDef[] = [
  {
    field: 'name',
    headerName: 'Name',
    width: 200,
  },
  {
    field: 'description',
    headerName: 'Description',
    width: 110,
  },
];


export function PortfolioList() {
  const navigate = useNavigate();
  const [selection, setSelection] = useState<GridRowSelectionModel>([]);

  const { data, error, loading } = useQuery<PortfoliosQuery, PortfoliosQueryVariables>(LIST_PORTFOLIOS, {
    fetchPolicy: 'cache-first',
  });
  function selectionCanged(selection: GridRowSelectionModel) {
    console.debug("[LineitemListComponent.selectionCanged]", selection);
    setSelection(selection);
  }
  function addPortfolio() {
    navigate('portfolios/new');
  }
  if (error) console.error(error);
  if (data) console.debug("[PortfolioList]", data);
  return (
    <Card elevation={6}>
      <CardHeader title={'Portfolios'} />
      <CardHeader subheader={'Click on a Portfolio to see details'} />
      <CardActionArea sx={{ ml: 2 }}>
        <ButtonGroup variant="contained" aria-label="activation-group">
          <Button onClick={addPortfolio}>New portfolio</Button>
        </ButtonGroup>
      </CardActionArea>
      <CardContent >
        {error && <ErrorNofification error={error} />}

        <DataGrid
          className='DataGrid'
          rows={(data?.portfolios) ? data?.portfolios : [] as any}
          columns={columns}
          loading={loading}
          onRowClick={(row) => {
            navigate(`${row.row.id}`);
          }
          }
          onRowSelectionModelChange={selectionCanged}
        />
      </CardContent>
    </Card>
  );
}
