// frontend/angular/src/app/retailer-details/retailer-details.component.ts
import { Component } from '@angular/core';
import { Retailer, RetailerQuery, RetailerQueryVariables, RetailerStatus } from 'not-dsp-graphql';
import { RETAILER_DETAILS } from 'not-dsp-graphql';
import { ActivatedRoute } from '@angular/router';
import { Apollo } from 'apollo-angular';

@Component({
  selector: 'app-retailer-details',
  templateUrl: './retailer-details.component.html',
  styleUrls: ['./retailer-details.component.css']
})
export class RetailerDetailsComponent {

  retailer: Retailer | undefined = undefined;
  loading: boolean = true;
  error: any;

  statuses: string[] = Object.values(RetailerStatus);

  constructor(private apollo: Apollo, private route: ActivatedRoute) { }

  ngOnInit(): void {
    const id = this.route.snapshot.params['retailerId'];
    this.apollo.watchQuery<RetailerQuery, RetailerQueryVariables>({
      query: RETAILER_DETAILS,
      variables: {
        retailerId: id
      }
    }).valueChanges.subscribe((result) => {
      console.log(result);
      this.retailer = result.data.retailer ? result.data.retailer as Retailer : undefined;
      this.loading = result.loading;
      this.error = result.errors;
    });
  }
  saveDetails(form: any) {
    alert('Retailer Form Validated)' + JSON.stringify(form.value, null, 4));
  }
}




  <mat-card>
    <mat-card-header>
      <mat-card-title>Retailer</mat-card-title>
      <div *ngIf="loading">
        <mat-progress-bar mode="indeterminate"></mat-progress-bar>
      </div>
      <div *ngIf="error">
        <p>Error: {{ error }}</p>
      </div>
    </mat-card-header>
    <mat-card-content>
      <div *ngIf="retailer" >
      <p>
        <mat-form-field class="formField">
          <mat-label>ID:</mat-label>
          <input matInput value="{{retailer.id}}" readonly>
        </mat-form-field>
      </p>

      <p>
        <mat-form-field class="formField">
          <mat-label>Name:</mat-label>
          <input matInput value="{{retailer.name}}" >
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Status:</mat-label>
          <input matInput value="{{retailer.status}}" >
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Country of origin:</mat-label>
          <input matInput value="{{retailer.countryOfOrigin}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Ranking:</mat-label>
          <input matInput value="{{retailer.rank}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Retail revenue USD millions:</mat-label>
          <input matInput value="{{retailer.retailRevenue}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Operational format:</mat-label>
          <input matInput value="{{retailer.operationalFormat}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Number countries of operation:</mat-label>
          <input matInput value="{{retailer.countriesOfOperation}}">
        </mat-form-field>
      </p>
      <app-campaign-list></app-campaign-list>
    </div>
    </mat-card-content>
  </mat-card>

// frontend/react/src/components/RetailerDetails.tsx

import { useQuery } from '@apollo/client';
import { useParams } from 'react-router-dom';
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Card, CardContent, CardHeader, LinearProgress,
  Paper, Stack, TextField, Typography
} from '@mui/material';
// import FormControl from '@mui/material/FormControl';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { RetailerQuery, RetailerQueryVariables } from 'not-dsp-graphql';
import { RETAILER_DETAILS } from 'not-dsp-graphql';
import { CampaignList } from './CampaignList';
import { ErrorNofification } from './error/ErrorBoundary';
import { AccountList } from './AccountList';

export function RetailerDetails() {
  const params = useParams();

  const { data, loading, error } = useQuery<RetailerQuery, RetailerQueryVariables>(RETAILER_DETAILS,
    {
      variables: {
        retailerId: params.retailerId || 'no-id',
      }
    });

  console.log('params', params);
  return (
    <Paper square={false}
      elevation={6}
      sx={{
        '& .MuiTextField-root': { m: 1, width: '55ch' },
      }}>
      <Card>
        <CardHeader
          title={'Retailer'}
        />
        <CardContent
          component="form"
          noValidate
          autoComplete="off"
        >
          {loading && <LinearProgress variant="query" />}
          {error && <ErrorNofification error={error} />}
          <Stack >
            <TextField
              label="ID"
              value={(data && data.retailer) ? data?.retailer?.id : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Name"
              value={(data && data.retailer) ? data?.retailer?.name : ''} />
            <TextField
              label="Status"
              value={(data && data.retailer) ? data?.retailer?.status : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Country of Origin"
              value={(data && data.retailer) ? data?.retailer?.countryOfOrigin : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Ranking"
              value={(data && data.retailer) ? data?.retailer?.rank : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Retail Revenue (m) USD"
              value={(data && data.retailer) ? data?.retailer?.retailRevenue : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Operational Format"
              value={(data && data.retailer) ? data?.retailer?.operationalFormat : ''}
              InputProps={{
                readOnly: true,
              }} />
            <TextField
              label="Number countries of operation"
              value={(data && data.retailer) ? data?.retailer?.countriesOfOperation : ''}
              InputProps={{
                readOnly: true,
              }} />
          </Stack>

          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="campaigns-content"
              id="campaigns-header"
            >
              <Typography>Campaigns</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <CampaignList retailerId={params.retailerId} />
            </AccordionDetails>
          </Accordion>
          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="accounts-content"
              id="accounts-header"
            >
              <Typography>Accounts</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <AccountList retailerId={params.retailerId} />
            </AccordionDetails>
          </Accordion>
        </CardContent>
      </Card>
    </Paper >
  );
}
