// frontend/angular/src/app/retailer-list/retailer-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { Retailer, RetailersQuery, RetailersQueryVariables } from 'not-dsp-graphql';
import { ActivatedRoute, Router } from '@angular/router';
import { Apollo } from 'apollo-angular';
import { RETAILER_LIST } from 'not-dsp-graphql';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';

@Component({
  selector: 'app-retailer-list',
  templateUrl: './retailer-list.component.html',
  styleUrls: ['./retailer-list.component.css']
})
export class RetailerListComponent implements OnInit {

  displayedColumns: string[] = ['name', 'status', 'countryOfOrigin'];

  retailers: Retailer[] = [];
  loading: boolean = true;
  error: any;
  datasource = new MatTableDataSource<Retailer>();

  offset: number = 0;
  limit: number = 10;
  retailersCount: number = 10;

  retailersQuery: any | undefined;

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  constructor(private apollo: Apollo, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.retailersQuery = this.apollo.watchQuery<RetailersQuery, RetailersQueryVariables>({
      query: RETAILER_LIST,
      variables: {
        offset: this.offset,
        limit: this.limit
      },
    });

    this.retailersQuery.valueChanges.subscribe((result: any) => {
      this.retailers = result.data.retailers?.retailers ? result.data.retailers?.retailers as Retailer[] : [];
      this.datasource.data = this.retailers;
      this.loading = result.loading;
      this.error = result.errors;
      this.retailersCount = result.data.retailers?.totalCount || 10;
      this.offset = result.data.retailers?.offset || 0;
      this.limit = result.data.retailers?.limit || 10;
      console.log(result.data.retailers);
    });
  }

  ngAfterViewInit() {
    console.debug("ngAfterViewInit");
    this.paginator.page.subscribe(page => {
      this.offset = page.pageIndex * this.limit;
      this.limit = page.pageSize;
      console.debug("ngAfterViewInit", page, this.offset, this.limit);
      this.fetchMore();
    });
  }

  fetchMore() {

    console.debug("fetchMore", this.offset, this.limit, this.retailers.length);
    this.retailersQuery?.fetchMore({
      variables: {
        offset: this.offset,
        limit: this.limit
      },
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        // console.debug("updateQuery", prev, fetchMoreResult);
        if (!fetchMoreResult) return prev;
        console.debug("updateQuery prev", prev);
        console.debug('updateQuery fetchMore', fetchMoreResult);
        return Object.assign({}, prev, {
          retailers: {
            ...prev.retailers,
            retailers: [...fetchMoreResult.retailers.retailers],
          }
        });
      }
    });
    return;
  }

  clickedRow(row: Retailer) {
    console.log(row);
    this.router.navigate(['/retailers', row.id]);
  }

}



<mat-card class="retailer-list">
  <mat-card-header>
    <mat-card-title>Retailers</mat-card-title>
    <mat-card-subtitle>Click on a Retailer to see details</mat-card-subtitle>
  </mat-card-header>
  <mat-card-content>
    <mat-progress-bar *ngIf="loading" mode="indeterminate"></mat-progress-bar>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
    <mat-table [dataSource]="datasource" >
      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef> Name </th>
        <td mat-cell *matCellDef="let element"> {{element.name}} </td>
      </ng-container>
      <ng-container matColumnDef="status">
        <th mat-header-cell *matHeaderCellDef> Status </th>
        <td mat-cell *matCellDef="let element"> {{element.status}} </td>
      </ng-container>
      <ng-container matColumnDef="countryOfOrigin">
        <th mat-header-cell *matHeaderCellDef> Country of Origin </th>
        <td mat-cell *matCellDef="let element"> {{element.countryOfOrigin}} </td>
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row (click)="clickedRow(row)" *matRowDef="let row; columns: displayedColumns;"></tr>
    </mat-table>
    <mat-paginator #paginator
      [pageSizeOptions]="[5, 10, 20]"
      [pageSize]="limit"
      showFirstLastButtons
      [length]="retailersCount"
      aria-label="Select page of Retailers ">
    </mat-paginator>
  </mat-card-content>
</mat-card>

// frontend/react/src/components/RetailerList.tsx
import {
  RetailersQuery,
  RetailersQueryVariables,
  RetailerList as Retailers,
} from 'not-dsp-graphql';
import { useNavigate } from 'react-router-dom';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { Card, CardContent, CardHeader } from '@mui/material';
import { QueryResult, useQuery } from '@apollo/client';
import { RETAILER_LIST } from 'not-dsp-graphql';
import { useEffect, useState } from 'react';
import { LIMIT_DEFAULT, OFFSET_DEFAULT } from '../lib/ListDefaults';
import { ErrorNofification } from './error/ErrorBoundary';

const columns: GridColDef[] = [
  // { field: 'id', headerName: 'ID', width: 90 },
  {
    field: 'name',
    headerName: 'Name',
    width: 200,
  },
  {
    field: 'status',
    headerName: 'Status',
    width: 110,
  },
  {
    field: 'countryOfOrigin',
    headerName: 'Country of Origin',
    width: 200,
    valueGetter: (params) => {
      return params.row.countryOfOrigin;
    },
  }

];



export function AllRetailerList() {
  const allRetailersQuery: QueryResult<RetailersQuery> = useQuery<RetailersQuery, RetailersQueryVariables>(RETAILER_LIST,
    {
      variables: {
        offset: OFFSET_DEFAULT,
        limit: LIMIT_DEFAULT,
      },
      fetchPolicy: 'cache-first'
    }
  );
  return (
    <RetailerList query={allRetailersQuery} />
  );
}

export function RetailerList(props: { query: QueryResult<RetailersQuery, RetailersQueryVariables>; }) {
  const navigate = useNavigate();
  const [retailerList, setRetailerList] = useState<Retailers>({ retailers: [], offset: OFFSET_DEFAULT, limit: LIMIT_DEFAULT, totalCount: LIMIT_DEFAULT });
  const { data, error, loading, fetchMore } = props.query;

  useEffect(() => {
    if (data && data.retailers) {
      setRetailerList({
        offset: data.retailers.offset || OFFSET_DEFAULT,
        limit: data.retailers.limit || LIMIT_DEFAULT,
        totalCount: data.retailers.totalCount || LIMIT_DEFAULT,
        retailers: data.retailers.retailers || []
      });
    }
  }, [data]);

  function fetchNext(offset: number, limit: number) {
    console.debug("[RetailerList.fetchNext]",
      offset, limit);
    fetchMore({
      variables: {
        offset,
        limit
      },
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        if (!fetchMoreResult) return prev;
        console.debug("[RetailerList.fetchNext.updateQuery]",
          prev,
          fetchMoreResult);
        setRetailerList({
          offset: fetchMoreResult.retailers.offset || retailerList.offset,
          limit: fetchMoreResult.retailers.limit || retailerList.limit,
          totalCount: fetchMoreResult.retailers.totalCount || retailerList.totalCount,
          retailers: fetchMoreResult.retailers.retailers || []
        });
      }
    });
    return;
  }
  console.log('[RetailerList] result', data, error, loading);
  console.log('[RetailerList] pagination', retailerList);

  return (
    <Card elevation={6} >
      <CardHeader title={'Retailers'} />
      <CardHeader subheader={'Click on a Retailer to see details'} />
      <CardContent>
        {error && <ErrorNofification error={error} />}
        <DataGrid
          sx={{ minHeight: 400 }}
          rows={(retailerList.retailers) ? retailerList.retailers : []}
          columns={columns}
          loading={loading}
          initialState={{
            pagination: {
              paginationModel: {
                pageSize: LIMIT_DEFAULT,
                page: OFFSET_DEFAULT / LIMIT_DEFAULT,
              },
            },
          }}
          rowCount={retailerList.totalCount || 0}
          paginationMode='server'
          pageSizeOptions={[LIMIT_DEFAULT]}
          onPaginationModelChange={({ pageSize, page }) => {
            console.debug("[RetailerList.onPaginationModelChange]", page, pageSize);
            fetchNext(pageSize * page, pageSize);
          }}
          onRowClick={(row) => navigate(`${row.row.id}`)}
        />
      </CardContent>
    </Card>
  );
}
