// frontend/react/src/components/BrandList.tsx
import { useQuery } from '@apollo/client';
import { Alert, AlertTitle, Box, Card, CardContent, CardHeader, Paper, Snackbar, Typography } from '@mui/material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { BRANDS_LIST } from 'not-dsp-graphql';
import { BrandsQuery, BrandsQueryVariables, BrandList as Brands } from 'not-dsp-graphql';
import { LIMIT_DEFAULT, OFFSET_DEFAULT } from '../lib/ListDefaults';
import { ErrorBoundary, ErrorNofification } from './error/ErrorBoundary';

const columns: GridColDef[] = [
  // { field: 'id', headerName: 'ID', width: 90 },
  {
    field: 'name',
    headerName: 'Name',
    width: 150,
  },
  {
    field: 'brandValue',
    headerName: 'Brand Value USD',
    width: 150,
  },
  {
    field: 'country',
    headerName: 'Country',
    width: 150,
  },
  {
    field: 'industry',
    headerName: 'Industry',
    width: 450,
  },


];

export function BrandList() {
  const navigate = useNavigate();
  const [brandList, setBrandList] = useState<Brands>({ brands: [], offset: OFFSET_DEFAULT, limit: LIMIT_DEFAULT, totalCount: LIMIT_DEFAULT });
  const { data, error, loading, fetchMore } = useQuery<BrandsQuery, BrandsQueryVariables>(
    BRANDS_LIST,
    {
      variables: {
        offset: brandList.offset,
        limit: brandList.limit,
      },
      fetchPolicy: 'cache-first',
    }
  );

  useEffect(() => {
    if (data && data.brands) {
      setBrandList({
        offset: data.brands.offset || OFFSET_DEFAULT,
        limit: data.brands.limit || LIMIT_DEFAULT,
        totalCount: data.brands.totalCount || LIMIT_DEFAULT,
        brands: data.brands.brands || []
      });
    }
  }, [data]);

  function fetchNext(offset: number, limit: number) {
    console.debug("[BrandList.fetchNext]",
      offset, limit);
    fetchMore({
      variables: {
        offset,
        limit
      },
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        if (!fetchMoreResult) return prev;
        console.debug("[BrandList.fetchNext.updateQuery]",
          prev,
          fetchMoreResult);
        setBrandList({
          offset: fetchMoreResult.brands.offset || brandList.offset,
          limit: fetchMoreResult.brands.limit || brandList.limit,
          totalCount: fetchMoreResult.brands.totalCount || brandList.totalCount,
          brands: fetchMoreResult.brands.brands || []
        });
      }
    });
    return;
  }


  console.log('[BrandList] result', data, error, loading);
  console.log('[BrandList] pagination', brandList);
  return (
    <ErrorBoundary>
      <Card elevation={6}>
        <CardHeader title={'Brands'} />
        <CardHeader subheader={'Click on a Brand to see details'} />
        <CardContent>
          {error && <ErrorNofification error={error} />}
          <DataGrid
            className='DataGrid'
            rows={(brandList && brandList.brands) ? brandList.brands : []}
            columns={columns}
            loading={loading}
            initialState={{
              pagination: {
                paginationModel: {
                  pageSize: LIMIT_DEFAULT,
                  page: OFFSET_DEFAULT / LIMIT_DEFAULT,
                },
              },
            }}
            rowCount={brandList.totalCount || LIMIT_DEFAULT}
            pageSizeOptions={[LIMIT_DEFAULT]}
            paginationMode="server"
            onPaginationModelChange={({ pageSize, page }) => {
              console.debug("[BrandList.onPaginationModelChange]", page, pageSize);
              fetchNext(pageSize * page, pageSize);
            }}
            onRowClick={(row) => navigate(`${row.row.id}`)}
          />
        </CardContent>
      </Card>
    </ErrorBoundary>
  );
}

// frontend/angular/src/app/brand-list/brand-list.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { Brand, BrandsQuery, BrandsQueryVariables } from 'not-dsp-graphql';
import { BRANDS_LIST } from 'not-dsp-graphql';
import { Apollo, QueryRef } from 'apollo-angular';
import { ActivatedRoute, Router } from '@angular/router';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'app-brand-list',
  templateUrl: './brand-list.component.html',
  styleUrls: ['./brand-list.component.css']
})
export class BrandListComponent implements OnInit {
  displayedColumns: string[] = ['name', 'value', 'country', 'industry'];

  brands: Brand[] = [];
  loading: boolean = true;
  error: any;
  datasource = new MatTableDataSource<Brand>();

  offset: number = 0;
  limit: number = 10;
  brandsCount: number = 10;

  page: number = 0;

  brandsQuery: any | undefined;

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  constructor(private apollo: Apollo, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.brandsQuery = this.apollo.watchQuery<BrandsQuery, BrandsQueryVariables>({
      query: BRANDS_LIST,
      variables: {
        offset: this.offset,
        limit: this.limit
      },
      fetchPolicy: 'cache-and-network'

    });

    this.brandsQuery.valueChanges.subscribe((result: any) => {
      this.brands = result.data.brands?.brands ? result.data.brands?.brands as Brand[] : [];
      this.datasource.data = this.brands;
      this.loading = result.loading;
      this.error = result.errors;
      this.brandsCount = result.data.brands?.totalCount || 10;
      this.offset = result.data.brands?.offset || 0;
      this.limit = result.data.brands?.limit || 10;
      this.page = this.offset / this.limit;
      console.log(result.data.brands);
    });
  }
  ngAfterViewInit() {
    console.debug("ngAfterViewInit");
    this.paginator.page.subscribe(page => {
      this.offset = page.pageIndex * this.limit;
      this.limit = page.pageSize;
      this.page = this.offset / this.limit;
      console.debug("ngAfterViewInit", page, this.offset, this.limit);
      this.fetchMore();
    });

    //https://github.com/abcox/toybox-web-ng2/blob/main/src/app/contact/contact-list/contact-list.component.ts
  }


  fetchMore() {

    console.debug("fetchMore", this.offset, this.limit, this.brands.length);
    this.brandsQuery?.fetchMore({
      variables: {
        offset: this.offset,
        limit: this.limit
      },
      updateQuery: (prev: any, { fetchMoreResult }: any) => {
        if (!fetchMoreResult) return prev;
        return Object.assign({}, prev, {
          brands: {
            ...prev.brands,
            brands: [...fetchMoreResult.brands.brands],
          }
        });
      }
    });
    return;
  }


  clickedRow(row: Brand) {
    console.log(row);
    this.router.navigate(['/brands', row.id]);
  }
};





<mat-card  class="mat-elevation-z8 brand-list">
  <mat-card-header>
    <mat-card-title>Brands</mat-card-title>
    <mat-card-subtitle>Click on a Brand to see details</mat-card-subtitle>
  </mat-card-header>
  <mat-card-content>
    <mat-progress-bar *ngIf="loading" mode="indeterminate"></mat-progress-bar>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
    <mat-table [dataSource]="datasource" >
      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef> Name </th>
        <td mat-cell *matCellDef="let element"> {{element.name}} </td>
      </ng-container>
      <ng-container matColumnDef="value">
        <th mat-header-cell *matHeaderCellDef> Brand Value USD </th>
        <td mat-cell *matCellDef="let element"> {{element.brandValue}} </td>
      </ng-container>
      <ng-container matColumnDef="country">
        <th mat-header-cell *matHeaderCellDef> Country </th>
        <td mat-cell *matCellDef="let element"> {{element.country}} </td>
      </ng-container>
      <ng-container matColumnDef="industry">
        <th mat-header-cell *matHeaderCellDef> Industry </th>
        <td mat-cell *matCellDef="let element"> {{element.industry}} </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row (click)="clickedRow(row)"
      *matRowDef="let row; columns: displayedColumns;"></tr>
    </mat-table>
    <mat-paginator #paginator
              [pageSizeOptions]="[5, 10, 20]"
              [pageSize]="limit"
              showFirstLastButtons
              [length]="brandsCount"
              aria-label="Select page of Brands ">
    </mat-paginator>
  </mat-card-content>
</mat-card>
