// frontend/react/src/components/CampaignDetails.tsx
import {
  Accordion, AccordionDetails, AccordionSummary, Box, Button,
  LinearProgress, MenuItem, Paper,
  Stack, TextField, Typography,
} from '@mui/material';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { DateRange, SingleInputDateRangeField } from '@mui/x-date-pickers-pro';
import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CAMPAIGNS_LIST, CAMPAIGN_DETAILS, CAMPAIGN_NEW } from '../graphql/campaigns.graphql';
import { ApolloError, useMutation, useQuery } from '@apollo/client';
import { LineitemList } from './LineitemList';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import {
  NewCampaign,
  NewCampaignMutation, NewCampaignMutationVariables,
  Campaign, CampaignType, CampaignStatus, BudgetType
} from '../graphql/types';
import dayjs, { Dayjs } from 'dayjs';

export function CampaignDetails() {
  const params = useParams();
  const navigate = useNavigate();

  const [isNew] = useState(params['campaignId'] === 'new');
  const [campaignId] = useState(params.campaignId || 'new');
  // campaign state
  const [campaign, setCampaign] = useState<Campaign>({
    id: '',
    name: '',
    type: CampaignType.CommerceDisplay,
    status: CampaignStatus.Inactive,
  });
  const accountId = useMemo(() => {
    return params.accountId as string;
  }, [params.accountId]);

  // Create Campaign
  const [addCampaign, { error: createError }] = useMutation<NewCampaignMutation, NewCampaignMutationVariables>(
    CAMPAIGN_NEW);

  // Fetch Campaign
  const { data, loading, error } = useQuery(CAMPAIGN_DETAILS,
    {
      variables: {
        campaignId: campaignId
      },
      skip: isNew,
    });

  useEffect(() => {
    if (data && data.campaign) {
      console.log('[CampaignDetails] data', data);
      setCampaign({
        ...data.campaign,
        startDate: new Date(data.campaign.startDate),
        endDate: new Date(data.campaign.endDate),
      } as Campaign);
    }
  }, [data]);

  function updateCampaign() {
    console.log('[CampaignDetails.updateCampaign] updating ', campaignId);
  }

  function newCampaign(newCampaign: NewCampaign) {
    console.log('[CampaignDetails.newCampaign]', newCampaign);
    addCampaign({
      variables: {
        advertiserId: accountId,
        campaign: newCampaign
      },
      refetchQueries: [{
        query: CAMPAIGNS_LIST,
        variables: {
          advertiserId: accountId,
        }
      }],
      onCompleted: (data: NewCampaignMutation) => {
        console.debug('[CampaignDetails.newCampaign]  completed', data);
        setCampaign(data?.newCampaign as Campaign);
        navigate(-1);
      },
      onError: (error: ApolloError) => {
        alert(`[CampaignDetails.newCampaign] error: ${error} `);
        console.error('[CampaignDetails.newCampaign] error', error);
      }
    });
  }

  function onSubmit(e: any) {
    e.preventDefault();
    console.log('[CampaignDetails.onSubmit] submitting', campaign, isNew);
    if (isNew) {

      const aNewCampaign: NewCampaign = {
        name: campaign.name || '',
        startDate: campaign.startDate || new Date(),
        endDate: campaign.endDate || new Date(),
        type: campaign.type,
        budget: {
          isCapped: false,
          type: BudgetType.Total,
          amount: 0
        }
      };
      newCampaign(aNewCampaign);
    } else {
      updateCampaign();
    }
  }

  const handleInputChange = (e: any) => {
    const { id, name, value } = e.target;
    setCampaign({
      ...campaign,
      [(name) ? name : id]: value,
    });
  };


  console.log('[CampaignDetails] campaign', campaign);
  const dates: DateRange<Dayjs> = [dayjs(campaign.startDate || new Date()), dayjs(campaign.endDate || new Date())];
  return (
    <Paper square={false}
      elevation={6}>
      <Box
        component="form"
        onSubmit={onSubmit}
        sx={{
          '& .MuiTextField-root': { m: 1, width: '45ch' },
        }}
        noValidate
        autoComplete="off"
        m={2}
      >
        {loading && <LinearProgress variant="query" />}
        {error && <p>Error: {error.message}</p>}
        {createError && <p>Create Error: {createError.message}</p>}
        <Typography variant="h4" gutterBottom>
          Campaign: {(data) ? data.campaign.id : ''}
        </Typography>
        <Button type="submit" variant='contained'>{isNew ? 'Create' : 'Save'}</Button>
        <Stack spacing={1}>
          <TextField
            label="Name"
            name='name'
            id="name"
            fullWidth
            required
            value={campaign.name}
            onChange={handleInputChange} />
          <Stack direction="row" spacing={2} sx={{ width: 400 }}>
            <TextField id="type" name="type"
              select
              value={campaign.type}
              onChange={handleInputChange}
              label="Type"
              required
            >
              {Object.values(CampaignType).map((type: any) => {
                return <MenuItem key={type} value={type}>{type.toString()}</MenuItem>;
              })
              }
            </TextField>
            {!isNew && <TextField id="status" name="status"
              select
              value={campaign.status}
              onChange={handleInputChange}
              label="Status"
              required
            >
              {Object.values(CampaignStatus).map((status: any) => {
                return <MenuItem key={status} value={status}>{status.toString()}</MenuItem>;
              })
              }
            </TextField>}
          </Stack>
          <DateRangePicker
            slots={{ field: SingleInputDateRangeField }}
            label="Start - End"
            localeText={{ start: 'start date', end: 'end date' }}
            value={dates}
            onChange={(newValue: DateRange<Dayjs>) => {
              console.log('[LineitemDetails] new DateRange', newValue);
              const startDate = newValue[0]?.toDate();
              const endDate = newValue[1]?.toDate();
              setCampaign({
                ...campaign,
                startDate: startDate,
                endDate: endDate
              });
            }}
          />
          {!isNew && <TextField
            label="Budget"
            value={campaign.budget?.amount || 0}
            type='number'
            onChange={handleInputChange} />}
        </Stack>
        {!isNew && <Accordion>
          <AccordionSummary
            expandIcon={<ExpandMoreIcon />}
            aria-controls="panel1a-content"
            id="panel1a-header"
          >
            <Typography>Lineitems</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <LineitemList campaignId={params.campaignId} />
          </AccordionDetails>
        </Accordion>}

      </Box >
    </Paper>
  );
}

// frontend/angular/src/app/campaign-details/campaign-details.component.ts
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { Apollo } from 'apollo-angular';
import {
  BudgetType, Campaign, CampaignQuery,
  CampaignQueryVariables, CampaignStatus,
  CampaignType, Lineitem, NewCampaign,
  NewCampaignMutation,
  NewCampaignMutationVariables
} from 'not-dsp-graphql';
import { ActivatedRoute, Router } from '@angular/router';
import { CAMPAIGNS_LIST, CAMPAIGN_DETAILS, CAMPAIGN_NEW } from 'not-dsp-graphql';

@Component({
  selector: 'app-campaign-details',
  templateUrl: './campaign-details.component.html',
  styleUrls: ['./campaign-details.component.css']
})
export class CampaignDetailsComponent {

  campaign: Campaign = {
    id: '',
    name: '',
    status: CampaignStatus.Unknown,
    type: CampaignType.Unknown,
    startDate: new Date(),
    endDate: new Date(),
  };
  loading: boolean = true;
  error: any;
  isNew: boolean = false;

  types: string[] = Object.values(CampaignType);
  statusValues: string[] = Object.values(CampaignStatus);


  lineitems: Lineitem[] = [];

  lineitemDisplayedColumns: string[] = ['id', 'name', 'status'];

  constructor(private apollo: Apollo,
    private route: ActivatedRoute,
    private router: Router,
    private location: Location) { }

  ngOnInit(): void {
    const id = this.route.snapshot.params['campaignId'];

    this.isNew = id === 'new';

    if (this.isNew) {
      console.debug('new campaign');
      this.loading = false;
    } else {
      this.apollo.watchQuery<CampaignQuery, CampaignQueryVariables>({
        query: CAMPAIGN_DETAILS,
        variables: {
          campaignId: id
        }
      }).valueChanges.subscribe((result) => {
        console.debug(result);
        this.campaign = result.data.campaign as Campaign;
        this.loading = result.loading;
        this.error = result.errors;
      });
    }
  }

  onFormSubmit() {
    console.debug('form submit', this.campaign);
    if (this.isNew) {
      this.createCampaign(this.campaign);
    } else {
      this.updateCampaign(this.campaign);
    }
  }

  createCampaign(form: any) {
    const accountId = this.route.snapshot.params['accountId'];
    console.debug('create campaign', this.campaign, this.route.snapshot.params);

    const newACampaign: NewCampaign = {
      name: this.campaign.name || '',
      startDate: this.campaign.startDate || new Date(),
      endDate: this.campaign.endDate || new Date(),
      type: this.campaign.type,
      budget: {
        isCapped: false,
        type: BudgetType.Total,
        amount: 0

      }
    };

    this.apollo.mutate<NewCampaignMutation, NewCampaignMutationVariables>({
      mutation: CAMPAIGN_NEW,
      variables: {
        advertiserId: accountId,
        campaign: newACampaign
      },
      refetchQueries: [{
        query: CAMPAIGNS_LIST,
      },
      {
        query: CAMPAIGN_DETAILS,
      }]

    }).subscribe(({ data, errors, loading }) => {
      if (errors) {
        console.error('Error creating campaign', errors);
        alert(`Error creating campaign: ${errors[0].message}`);
        this.location.back();
      }
      if (data) {
        console.debug('New campaign created', JSON.stringify(data, null, 2));
        const newCampaignId = (data as any).newCampaign.id;
        alert(`New campaign created, id: ${newCampaignId} `);
        this.location.back();
      }
    });

  }

  updateCampaign(form: any) {
    const accountId = this.route.snapshot.params['accountId'];
    const id = this.route.snapshot.params['campaignId'];

    alert(`Campaign updated, id: ${this.campaign?.id} (fake)`);
    console.debug('Update campaign', this.campaign);
    this.router.navigate(['/accounts', accountId, 'campaigns']);
  }
}



<mat-card>
  <mat-card-header>
    <mat-card-title>Campaign: {{campaign.id||''}}</mat-card-title>
    <div *ngIf="loading">
      <mat-progress-bar mode="indeterminate"></mat-progress-bar>
    </div>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
  </mat-card-header>
  <mat-card-content>
    <p>
      <mat-form-field appearance="fill">
        <mat-label>Name:</mat-label>
        <input matInput type="text" [(ngModel)]="campaign.name" >
      </mat-form-field>
    </p>

    <p>
      <mat-form-field appearance="fill" *ngIf="!isNew" >
        <mat-label>Status:</mat-label>
        <mat-select [(ngModel)]="campaign.status" >
          <mat-option *ngFor="let status of statusValues" [value]="status">
            {{status}}
          </mat-option>
        </mat-select>
      </mat-form-field>
    </p>

    <p>
      <mat-form-field appearance="fill" >
        <mat-label>Type:</mat-label>
        <mat-select [(ngModel)]="campaign.type" >
          <mat-option *ngFor="let type of types" [value]="type">
            {{type}}
          </mat-option>
        </mat-select>
      </mat-form-field>
    </p>
    <p>
      <mat-form-field appearance="fill"  >
        <mat-label>Campaign date range:</mat-label>
        <mat-date-range-input [rangePicker]="rangePicker">
          <input matStartDate placeholder="Start date" [(ngModel)]="campaign.startDate">
          <input matEndDate placeholder="End date" [(ngModel)]="campaign.endDate">
        </mat-date-range-input>
        <mat-datepicker-toggle matSuffix [for]="rangePicker"></mat-datepicker-toggle>
        <mat-date-range-picker #rangePicker>
          <mat-date-range-picker-actions>
            <button mat-button matDateRangePickerCancel>Cancel</button>
            <button mat-raised-button color="primary" matDateRangePickerApply>Apply</button>
          </mat-date-range-picker-actions>
        </mat-date-range-picker>
      </mat-form-field>
    </p>
  </mat-card-content>
  <mat-card-actions>
    <button mat-raised-button color="primary" (click)="onFormSubmit()">{{(isNew)?'Create':'Save'}}</button>
  </mat-card-actions>
  <div *ngIf="!isNew">
    <app-lineitem-list/>
  </div>
</mat-card>
