// frontend/react/src/components/ProductDetails.tsx

import { useQuery } from '@apollo/client';
import { useParams } from 'react-router-dom';
import {
  Box, Card, CardContent, CardHeader, FormControl,
  LinearProgress, Paper, TextField
} from '@mui/material';
import { SkuQuery, SkuQueryVariables } from 'not-dsp-graphql';
import { PRODUCT_DETAILS } from 'not-dsp-graphql';
import { Scalars } from 'not-dsp-graphql';
import { ErrorNofification } from './error/ErrorBoundary';

export interface ProductDetailsProps {
  skuKey?: Scalars['ID'];
}

export function ProductDetails(props: ProductDetailsProps) {
  const params = useParams();

  const { data, loading, error } = useQuery<SkuQuery, SkuQueryVariables>(PRODUCT_DETAILS,
    {
      variables: {
        skuKey: (props.skuKey) ? props.skuKey : params.skuKey || 'no-id',
      }
    });

  console.log('params', params);
  return (
    <Paper
      square={false}
      elevation={6} >
      <Card>
        <CardHeader
          title={'PRODUCT'}
        />
        <CardContent>
          <Box
            component="form"
            sx={{
              '& .MuiTextField-root': { m: 1, width: '55ch' },
            }}
            noValidate
            autoComplete="off"
            m={2}
          >
            {loading && <LinearProgress variant="query" />}
            {error && <ErrorNofification error={error} />}
            <FormControl >
              <TextField
                label="Key"
                value={(data && data.sku) ? data?.sku?.skuKey : ''}
                InputProps={{
                  readOnly: true,
                }} />
              <TextField
                label="Name"
                value={(data && data.sku) ? data?.sku?.name : ''}
                multiline={true}
                rows={2} />
              <TextField
                label="Description"
                value={(data && data.sku) ? data?.sku?.description : ''}
                multiline={true}
                rows={5} />
              <TextField
                label="Price"
                value={(data && data.sku) ? data?.sku?.price : 0}
                type='number' />
              <TextField
                label="Quantity"
                value={(data && data.sku) ? data?.sku?.quantity : 0}
                type='number'
              />
            </FormControl >
          </Box>
        </CardContent>
      </Card>
    </Paper>
  );
}

// frontend/angular/src/app/product-details/product-details.component.ts
import { Component } from '@angular/core';
import { Sku, SkuQuery, SkuQueryVariables } from 'not-dsp-graphql';
import { Apollo } from 'apollo-angular';
import { ActivatedRoute } from '@angular/router';
import { PRODUCT_DETAILS } from 'not-dsp-graphql';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css']
})
export class ProductDetailsComponent {

  sku: Sku | undefined = undefined;
  loading: boolean = true;
  error: any;


  constructor(private apollo: Apollo, private route: ActivatedRoute) { }

  ngOnInit(): void {
    const id = this.route.snapshot.params['skuKey'];
    this.apollo.watchQuery<SkuQuery, SkuQueryVariables>({
      query: PRODUCT_DETAILS,
      variables: {
        skuKey: id
      }
    }).valueChanges.subscribe((result) => {
      console.log(result);
      this.sku = result.data.sku ? result.data.sku as Sku : undefined;
      this.loading = result.loading;
      this.error = result.errors;
    });
  }
  saveDetails(form: any) {
    console.debug("[ProductListComponent.saveDetails] clicked");
    alert('Product Form Validated)' + JSON.stringify(form.value, null, 4));
  }
}



<mat-card>
  <mat-card-header>
    <mat-card-title>SKU details</mat-card-title>
    <div *ngIf="loading">
      <mat-progress-bar mode="indeterminate"></mat-progress-bar>
    </div>
    <div *ngIf="error">
      <p>Error: {{ error }}</p>
    </div>
  </mat-card-header>
  <mat-card-content>
    <div *ngIf="sku">
      <p>
        <mat-form-field class="formField">
          <mat-label>Key:</mat-label>
          <input matInput value="{{(sku.skuKey)?sku.skuKey:''}}" readonly>
        </mat-form-field>
      </p>

      <p>
        <mat-form-field class="formField">
          <mat-label>Name:</mat-label>
          <input matInput value="{{sku.name}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField" rows="6">
          <mat-label>Description:</mat-label>
          <textarea matInput >
            {{sku.description}}
          </textarea>
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Price:</mat-label>
          <input matInput value="{{sku.price}}">
        </mat-form-field>
      </p>
      <p>
        <mat-form-field class="formField">
          <mat-label>Quantity:</mat-label>
          <input matInput value="{{sku.quantity}}">
        </mat-form-field>
      </p>
    </div>
  </mat-card-content>
</mat-card>
